name: "OpenSprinkler"
version: "2.1.0"
slug: "opensprinkler"
description: "Full OpenSprinkler Unified Firmware running as a local Add-on."
url: "https://github.com/OpenSprinkler/OpenSprinkler-Firmware"
startup: application
arch:
  - aarch64
  - amd64
  - armv7

options:
  admin_password: "opendoor"
schema:
  admin_password: str
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
panel_icon: "mdi:water-pump"
panel_admin: true

init: false
